"""Deterministic extraction of common 10-K financial tables, with source lineage."""

from __future__ import annotations

import re
from dataclasses import dataclass

from langchain_core.documents import Document


@dataclass(frozen=True)
class ExtractedFact:
    metric_name: str
    metric_category: str
    value: float
    fiscal_year: int
    page_number: int | None
    section_name: str | None
    source_chunk_id: str
    unit: str = "USD_millions"
    currency: str = "USD"
    confidence: float = 0.95


_GEO = {"Americas": "americas_revenue", "Europe": "europe_revenue", "Greater China": "greater_china_revenue", "Japan": "japan_revenue", "Rest of Asia Pacific": "rest_of_asia_pacific_revenue"}
_PRODUCT = {"iPhone": "iphone_revenue", "Mac": "mac_revenue", "iPad": "ipad_revenue", "Wearables, Home and Accessories": "wearables_revenue", "Services": "services_revenue"}
_ROWS = {
    "Total net sales": ("total_revenue", "revenue"), "Gross margin": ("gross_profit", "profitability"),
    "Operating income": ("operating_income", "profitability"), "Net income": ("net_income", "profitability"),
    "Cash generated by operating activities": ("operating_cash_flow", "cash_flow"),
    "Payments for acquisition of property, plant and equipment": ("capex", "cash_flow"),
    "Payments for dividends and dividend equivalents": ("dividends", "cash_flow"),
    "Repurchases of common stock": ("share_repurchases", "cash_flow"),
}


def _numbers(line: str) -> list[float]:
    # Rows on 10-K tables contain amounts with comma separators. Percent fields are ignored.
    values = []
    for raw in re.findall(r"\(?\$?\s*\d{1,3}(?:,\d{3})+(?:\.\d+)?\)?", line):
        negative = raw.strip().startswith("(")
        number = float(re.sub(r"[^\d.]", "", raw))
        values.append(-number if negative else number)
    return values


def _years(text: str, fallback: int | None) -> list[int]:
    years = []
    for raw in re.findall(r"\b20\d{2}\b", text[:1200]):
        value = int(raw)
        if value not in years:
            years.append(value)
    return years[:3] if len(years) >= 3 else ([fallback, fallback - 1, fallback - 2] if fallback else [])


def extract_financial_facts(chunks: list[Document], chunk_ids: list[str]) -> list[ExtractedFact]:
    facts: list[ExtractedFact] = []
    for chunk, chunk_id in zip(chunks, chunk_ids):
        text = chunk.page_content
        meta = chunk.metadata
        years = _years(text, meta.get("fiscal_year"))
        if not years:
            continue
        labels = {**_GEO, **_PRODUCT}
        for label, metric in labels.items():
            row = next((line for line in text.splitlines() if line.strip().lower().startswith(label.lower())), None)
            if not row:
                continue
            values = _numbers(row)
            if len(values) >= len(years):
                category = "geography" if label in _GEO else "revenue"
                facts.extend(ExtractedFact(metric, category, value, year, meta.get("page_number"), meta.get("section_name"), chunk_id) for year, value in zip(years, values[:len(years)]))
        for label, (metric, category) in _ROWS.items():
            row = next((line for line in text.splitlines() if line.strip().lower().startswith(label.lower())), None)
            if not row:
                continue
            values = _numbers(row)
            if len(values) >= len(years):
                facts.extend(ExtractedFact(metric, category, value, year, meta.get("page_number"), meta.get("section_name"), chunk_id) for year, value in zip(years, values[:len(years)]))
    return facts
